### ISSUE TITLE
1.20.1 crash from version 1.3.0

### ISSUE THREAD

**Issue by Alwis2000** [AV306/KeybindsGalore-Plus#6]
Made sure its related to this mod by running a seperate instance where its only this mod. Tried the config changes too as suggested from the changelogs, Deleted it, took it from github and turned off some of the new features just in case but nothing worked. Reverted back to 1.1.0 and that works as expected. 

I love the mod and I appreciate you keeping it going and adding new features! 

Crash logs if needed:
https://mclo.gs/zwuDkxH

**Comment by AV306** [comment]
Oh nooo I made this mistake again, I'm so sorry 😭 

It crashes because I mistakenly compiled the 1.20.x version with Java 21, so you need at least Java 21 to run it (you were using Java 17).

I'll recompile and reupload it in a few days; I'm really sorry for the inconvenience :(

Thanks for your support :)

**Comment by AV306** [comment]
It should be fixed now, you can try the new build at https://modrinth.com/mod/keybindsgaloreplus/version/XWUAC2dC :D

**Comment by Alwis2000** [comment]
Nice! thanks for giving your time to fix it :]
